# Generated by Django 4.1 on 2025-07-19 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Remote_User', '0007_clientposts_model_names'),
    ]

    operations = [
        migrations.CreateModel(
            name='detection_accuracy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(max_length=300)),
                ('ratio', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='detection_ratio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(max_length=300)),
                ('ratio', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Job_Post_Prediction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Job_Id', models.CharField(max_length=300)),
                ('Actual_Fake', models.CharField(max_length=300)),
                ('Predicted_Fake', models.CharField(max_length=300)),
                ('Prediction_Details', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Prediction_Results',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Job_Id', models.CharField(max_length=300)),
                ('Actual_Fake', models.CharField(max_length=300)),
                ('Predicted_Fake', models.CharField(max_length=300)),
            ],
        ),
        migrations.RemoveField(
            model_name='clientposts_model',
            name='userId',
        ),
        migrations.DeleteModel(
            name='review_Model',
        ),
        migrations.AlterField(
            model_name='clientregister_model',
            name='city',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='clientregister_model',
            name='country',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='clientregister_model',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='clientregister_model',
            name='password',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='clientregister_model',
            name='phoneno',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='clientregister_model',
            name='state',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='clientregister_model',
            name='username',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='ClientPosts_Model',
        ),
    ]
