# Generated by Django 4.1 on 2025-07-19 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Remote_User', '0008_detection_accuracy_detection_ratio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientregister_model',
            name='city',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='clientregister_model',
            name='country',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='clientregister_model',
            name='email',
            field=models.EmailField(max_length=30),
        ),
        migrations.AlterField(
            model_name='clientregister_model',
            name='password',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='clientregister_model',
            name='phoneno',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='clientregister_model',
            name='state',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='clientregister_model',
            name='username',
            field=models.CharField(max_length=30),
        ),
    ]
